language: node_js
sudo: false
node_js:
- '6'
branches:
  only:
  - master
  - develop
env:
  global:
  - GIT_COMMITTER_NAME=travis-ci
  - GIT_COMMITTER_EMAIL=inc@2inc.org
  - GIT_AUTHOR_NAME=travis-ci
  - GIT_AUTHOR_EMAIL=inc@2inc.org
  - secure: "hYCrLgaMQyKj6+vrkMzfbk+MrCn+HUmI8s/CacXa6www1p5r0kqAaU+asZ8X2FTHpVbWoFiMY5W2KEjKTbkru7Bw9BKItlKQJ7KG9xuRZNeMmVkN1e8zHuWyluCZovD6FCcrtgJd2fhSgNyain1xDsE0Rs3EL/utU/tRo2G8lseI5IEet7Vb6ah5Yn3AK+iEAIE3uCqNZgxwRVHgi4VeGCPpzbNO9mE4mtl+ytM0mEPiVNR4hyTkM8RF8QLUzxGA4OaPJ+oORq6wQTOx7iJTfpttw4qODwzBrYowKAnMlYJ4JbjiZZegItJcM2JsE7BZxjvjLTINAQZ1DXJwTPRSPQt9oRghJfKJjJ88YcIgdsOde0KjRkMkCmB1qMPbcjrn2RQWOURf/VRjDITYi1jb+G+V4ioQoRPeLqC225QGk0OBrfGmInW7QoLYvdowLG1e/qnmW3okJMHZU2JVfjBjgJS5NayxKwv2Mk7i1Th8bMAT/NVQ4RKsdI5G6GJmsWqYjqOi4vFStkru45Lw0ZSAJnv7EEoc16yf/+VX85TY7TD0hvkUW6LSU5yXfWX3mwrsRLinnEjbTtIceIxuvcDQo5vaTgIJC+QF1ICIHQQGCwnOZ9pkq0g6cr21ZdmYxJj5HDKdHoiyCpuvDhY11LE2pPibO1fcBvf2QDhPx5pnvcA="
install:
- npm install
script:
- npm run gulp build
after_success:
- bash ./bin/deploy.sh
