language: node_js
sudo: false
node_js:
  - '6'
branches:
  only:
    - master
    - develop
env:
  global:
    - GIT_COMMITTER_NAME=travis-ci
    - GIT_COMMITTER_EMAIL=inc@2inc.org
    - GIT_AUTHOR_NAME=travis-ci
    - GIT_AUTHOR_EMAIL=inc@2inc.org
    - secure: "GlGm3Lf3jHhO9yCcN6ZlwaiYxw3ET5gYz9O3s7LGGRIwwT2J8znvD1cHtvzNw8CBXQtYOUGH6K5MAXBMxfyKlCzFIUbdoxpSUMqu9ETVEo7dt8D7EtKG+3Q75+54N5W0MIfz1NsMUWzovyeCftaocRyUQReQNvn8/e3BhstFQ/AcPZvwGDsbZi1CjtsP1WwQlbesusyPlEyFVjze6I4bAFvgpiv/EZnaDZvc9ZG1qj7UWM/EEh0RAXuYdW/uF2HhCca2BMEQqTW4f6fOXh/dGVGcapYZJN/t80y5RHI4OWf/yW2KGDg+XTdwQ8DXnodzh3cUGpVOSojZCb8ValWbdX9vJOURenc2iJA6uTSh3e0GPCugT3wXLKLwR4gmM3PCbwevaYS1aNu+hMYSVM7+V37SQXEhdw8jtseEerjahNRrX/eTF6ug3sp1VufypXLrDJ3jqqNAwIvS4dLo+1aQh8wvueS4HVPjWQAMAukiFfQf/Tnmm3Is4uV0vfQoRAH8l7mBOcRk9JrTCWffVmLGj8GjKb+0tN0c8wLRAvnvAnH3OQRuGhMOfaie02nsIEwgAOp2XbioocRMxHi/m/jcUVpH3/7BEY/SxCw9cNMrsa64TyS9kQWh6c6OkC6Kr/PcltJh9x2qP8653y5usgRXSfwxM+iLyz27lsVcoDSstPk="
before_deploy:
  - npm run gulp build
deploy:
  - bash ./bin/deploy.sh
